spring:  application:    name: poc-camunda-bpm-spring-boot  datasource:      url: jdbc:mysql://localhost:3306/camundadb      driverClassName: com.mysql.cj.jdbc.Driver      username: root      password:  jpa:    show-sql: true    
camunda.bpm:
  admin-user:
    id: admin
    password: admin@123
    firstName: Admin User
  filter:
    create: All tasks