spring:
   application:
        name: pessoa-fisica-api
   profiles:
      active: local
   datasource:
      url: jdbc:sqlite:C:\\Spring\\workspaces\\poc-camunda-bpm-spring-boot\\pessoa-fisica.db
      driverClassName: org.sqlite.JDBC
      username: sa
      password: sa
   jpa:
      generate-ddl: true
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.SQLiteDialect
            show-sql: true
            hbm2ddl:
#               auto: create-drop
               auto: update
management:
   metrics:
      export:
         prometheus:
            enabled: true
   endpoint:
      prometheus:
         enabled: true
   web:
      exposure:
         include: health, info, prometheus
---
spring:
   profiles: local

---
spring:
   profiles: uat,prd
   
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.SQLiteDialect
            show-sql: true
            hbm2ddl:
               auto: update